name: Open Free macOS noVNC Web Session
on: workflow_dispatch

jobs:
  interactive-web-gui:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # 👇 Adding "detached: true" stops the action from looping/printing lines constantly
      - name: Open Secure Web Tunnel
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true